#!/usr/bin/env python3
"""Regenerate index.yaml from every packs/*/manifest.yaml (+ tiers.yaml).

Stopgap until `cortex packs index` (phase 1 of docs/marketplace.md) does this
in Rust; CI will fail if index.yaml is stale.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def scalar(text, key):
    m = re.search(rf"^{key}: (.*)$", text, re.M)
    if not m:
        return None
    v = m.group(1).strip()
    if v.startswith('"') and v.endswith('"'):
        v = v[1:-1].replace('\\"', '"')
    return v

def main():
    tiers = {}
    for line in (ROOT / "tiers.yaml").read_text().splitlines():
        if line and not line.startswith("#") and ":" in line:
            k, v = line.split(":", 1)
            tiers[k.strip()] = v.strip()
    out = ["# GENERATED by tools/gen_index.py from packs/*/manifest.yaml — do not edit by hand.", "format: 1", "packs:"]
    for mf in sorted(ROOT.glob("packs/*/manifest.yaml")):
        t = mf.read_text()
        pid = scalar(t, "id")
        if pid != mf.parent.name:
            sys.exit(f"{mf}: id {pid!r} != folder {mf.parent.name!r}")
        tags = scalar(t, "tags")
        out += [
            f"  - id: {pid}",
            f"    name: \"{scalar(t, 'name')}\"",
            f"    version: {scalar(t, 'version')}",
            f"    kind: {scalar(t, 'kind')}",
            f"    tier: {tiers.get(pid, 'community')}",
            f"    summary: \"{scalar(t, 'summary')}\"",
            f"    tags: {tags}",
            f"    license: {scalar(t, 'license')}",
        ]
    (ROOT / "index.yaml").write_text("\n".join(out) + "\n")
    print(f"index.yaml: {sum(1 for _ in ROOT.glob('packs/*/manifest.yaml'))} packs")

if __name__ == "__main__":
    main()
